/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import modelos.Objeto;
import modelos.Vehiculo;
import modelos.Via;
import modelos.Carro;
import modelos.Hilo;

/**
 *
 * @author Lucas
 */
public class Pventana extends javax.swing.JPanel {

    Via via1, via2, via3;
    Objeto nube1, nube2, nube3, nube4, nube5, nube6, explosion;
    Carro vehiculo;
    Thread h1, h2, h3, h4, h5, h6, h7, h8;
    Hilo hilo1, hilo2;
    boolean bandera, bandera1 = false;
    ImageIcon imagenNuben = new ImageIcon(getClass().getResource("../img/nube.png"));
    ImageIcon imagenCarroFrente = new ImageIcon(getClass().getResource("../img/carro-frente.png"));
    ImageIcon imagenExplosion = new ImageIcon(getClass().getResource("../img/explosion.png"));
    /**
     * Creates new form Pventana
     */
    public Pventana() {
        initComponents();
        this.via1 = new Via(0,0,640,160);
        this.via2 = new Via(570,0,640,160);
        this.via3 = new Via(0,0,640,160);
        this.nube1 = new Objeto(10, 10, 40, 30, imagenNuben);
        this.nube2 = new Objeto(70, 10, 40, 30, imagenNuben);
        this.nube3 = new Objeto(130, 10, 40, 30, imagenNuben);
        this.nube4 = new Objeto(310, 10, 40, 30, imagenNuben);
        this.nube5 = new Objeto(370, 10, 40, 30, imagenNuben);
        this.nube6 = new Objeto(430, 10, 40, 30, imagenNuben);
        this.h3 = new Thread(this.via3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
            
            g.drawImage(this.via3.getImagen().getImage(), this.via3.getX(), 
                this.via3.getY(), this.via3.getAncho(), this.via3.getAlto(), this);
            g.drawImage(this.via1.getImagen().getImage(), this.via1.getX(), 
                this.via1.getY(), this.via1.getAncho(), this.via1.getAlto(), this);
            g.drawImage(this.via2.getImagen().getImage(), this.via2.getX(), 
                this.via2.getY(), this.via2.getAncho(), this.via2.getAlto(), this);
            
            if(this.via2.getX() == -150){
                this.via1.setX(400);
                this.bandera = true;
            }else if(this.via1.getX() < -140 && bandera){
                this.via2.setX(400);
                this.bandera = false;
            }
            
            g.drawImage(this.nube1.getImagen().getImage(), this.nube1.getX(), 
                 this.nube1.getY(), this.nube1.getAncho(), this.nube1.getAlto(), this);
            g.drawImage(this.nube2.getImagen().getImage(), this.nube2.getX(), 
                 this.nube2.getY(), this.nube2.getAncho(), this.nube2.getAlto(), this);
            g.drawImage(this.nube3.getImagen().getImage(), this.nube3.getX(), 
                    this.nube3.getY(), this.nube3.getAncho(), this.nube3.getAlto(), this);
            g.drawImage(this.nube4.getImagen().getImage(), this.nube4.getX(), 
                    this.nube4.getY(), this.nube4.getAncho(), this.nube4.getAlto(), this);
            g.drawImage(this.nube5.getImagen().getImage(), this.nube5.getX(), 
                    this.nube5.getY(), this.nube5.getAncho(), this.nube5.getAlto(), this);
            g.drawImage(this.nube6.getImagen().getImage(), this.nube6.getX(), 
                    this.nube6.getY(), this.nube6.getAncho(), this.nube6.getAlto(), this);
            
            if(vehiculo != null){
                g.drawImage(this.vehiculo.getImagen().getImage(), this.vehiculo.getX(), 
                 this.vehiculo.getY(), this.vehiculo.getAncho(), this.vehiculo.getAlto(), this);
            }
            if(explosion != null){
                g.drawImage(this.explosion.getImagen().getImage(), this.explosion.getX(), 
                 this.explosion.getY(), this.explosion.getAncho(), this.explosion.getAlto(), this);
            }
        repaint();
    }
    
    public void moverVia(int velocidad){
        
        this.via1.setVelocidad(velocidad);
        this.via2.setVelocidad(velocidad);
        //this.h1 = new Thread(this.via1);
        this.hilo1 = new Hilo("Hilo1");
        this.hilo1.inicia(this.via1);
        this.hilo2 = new Hilo("Hilo2");
        this.hilo2.inicia(this.via2);
        //this.h1.start();
        //this.h2 = new Thread(this.via2);
        //this.h2.start();
    }
    
    public void frenar(int velocidad){
       // this.h1.stop();
        //this.h2.stop();
        this.hilo1.parar();
        this.hilo2.parar();
        Hilo nuevoHilo1 = new Hilo("nuevoHilo1");
        Hilo nuevoHilo2 = new Hilo("nuevoHilo2");
        this.via1.setVelocidad(velocidad);
        this.via1.setVelocidad(velocidad);
        //this.h1 = new Thread(this.via1);
        //this.h1.start();
        nuevoHilo1.inicia(this.via1);
        nuevoHilo2.inicia(this.via1);
       // this.h2 = new Thread(this.via2);
        //this.h2.start();
    
    }
    
    public void crearVehiculo(){
        this.vehiculo = new Carro(60, 50, 100, 80, imagenCarroFrente);
    }
    
    public void patinar(){
        this.vehiculo.setBandera1(true);
        this.h4 = new Thread(this.vehiculo);
        this.h4.start();
    }
    
    public void explotar(){
        this.explosion = new Objeto(60, 50, 100, 80, imagenExplosion);
    }
    
    public void eliminarExplosion(){
        this.explosion = null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
