/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import modelos.Nube;
import modelos.Vehiculo;
import modelos.Via;

/**
 *
 * @author Lucas
 */
public class Pventana extends javax.swing.JPanel {

    Via nuevaVia;
    Nube nube1, nube2, nube3, nube4, nube5, nube6, nube7, nube8;
    Vehiculo vehiculo = new Vehiculo("Bonitas", 3000);
    /**
     * Creates new form Pventana
     */
    public Pventana() {
        initComponents();
        this.nuevaVia = new Via(0,0,500,160);
        this.nube1 = new Nube(10, 10, 40, 30);
        this.nube2 = new Nube(70, 10, 40, 30);
        this.nube3 = new Nube(130, 10, 40, 30);
        this.nube4 = new Nube(190, 10, 40, 30);
        this.nube5 = new Nube(250, 10, 40, 30);
        this.nube6 = new Nube(310, 10, 40, 30);
        this.nube7 = new Nube(370, 10, 40, 30);
        this.nube8 = new Nube(430, 10, 40, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        int x = 5;
        g.drawImage(this.nuevaVia.getImagen().getImage(), this.nuevaVia.getX(), 
                this.nuevaVia.getY(), this.nuevaVia.getAncho(), this.nuevaVia.getAlto(), this);
      
        g.drawImage(this.nube1.getImagen().getImage(), this.nube1.getX(), 
                this.nube1.getY(), this.nube1.getAncho(), this.nube1.getAlto(), this);
        g.drawImage(this.nube2.getImagen().getImage(), this.nube2.getX(), 
                this.nube2.getY(), this.nube2.getAncho(), this.nube2.getAlto(), this);
        g.drawImage(this.nube3.getImagen().getImage(), this.nube3.getX(), 
                this.nube3.getY(), this.nube3.getAncho(), this.nube3.getAlto(), this);
        g.drawImage(this.nube4.getImagen().getImage(), this.nube4.getX(), 
                this.nube4.getY(), this.nube4.getAncho(), this.nube4.getAlto(), this);
        g.drawImage(this.nube5.getImagen().getImage(), this.nube5.getX(), 
                this.nube5.getY(), this.nube5.getAncho(), this.nube5.getAlto(), this);
        g.drawImage(this.nube6.getImagen().getImage(), this.nube6.getX(), 
                this.nube6.getY(), this.nube6.getAncho(), this.nube6.getAlto(), this);
        g.drawImage(this.nube7.getImagen().getImage(), this.nube7.getX(), 
                this.nube7.getY(), this.nube7.getAncho(), this.nube7.getAlto(), this);
        g.drawImage(this.nube8.getImagen().getImage(), this.nube8.getX(), 
                this.nube8.getY(), this.nube8.getAncho(), this.nube8.getAlto(), this);
        
        repaint();
    }

    public void moverNube(){
        this.nube1.setX(this.nube1.getY() - 5);
        this.nube2.setX(this.nube1.getY() - 5);
        this.nube3.setX(this.nube1.getY() - 5);
        this.nube4.setX(this.nube1.getY() - 5);
        this.nube5.setX(this.nube1.getY() - 5);
        this.nube6.setX(this.nube1.getY() - 5);
        this.nube7.setX(this.nube1.getY() - 5);
        this.nube8.setX(this.nube1.getY() - 5);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
